### ISSUE TITLE
Documentation for initializing

### ISSUE THREAD

**Issue by Hraph** [evonove/planner.js#49]
Hi,
Do you have any documentation to initialise the planner with existing data?

**Comment by silvanocerza** [comment]
Hey there, sadly the project is not documented but there's an example on [here](https://github.com/evonove/planner.js/blob/master/client/js/main.js) using mocked data.

**Comment by Hraph** [comment]
Thank you, I'll manage with this example. It's a good project, simple and effective. Nice work!
